version: '3'

services:

  main:
    image: creigmac/ciscojenkins:latest
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
    volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass

 secrets:
    jenkins-user:
      external: true
    jenkins-pass:
      external: true
