version: '3.5'

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true


services:
  main:
    image: creigmac/ciscojenkins:latest
    command: ping docker.com
    secrets:
      - jenkins-user
      - jenkins-pass
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

    volumes:
      - "./var/jenkins_home:/jenkins_home"

    networks:
      - proxy

    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
networks:
  proxy:
    external: true
