version: '3.1'

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
volumes:
  jm:
    driver: cloudstor:aws
    driver_opts:
       size: "25"
    external: false

volumes:
   jmshare:
     driver: cloudstor:aws
     external: false

services:
  main:
    image: creigmac/ciscojenkins:latest
    secrets:
      - jenkins-user
      - jenkins-pass
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
